### ISSUE TITLE
Suites page 404s

### ISSUE THREAD

**Issue by walterbenson** [allure-framework/allure-ruby#127]
👋 Hi there! First off thanks for creating and maintaining this incredible tool.

We are seeing a bug where the suites page completely 404s because of some missing data. Having just one test like the following
```
describe
   it
```
rather than 
```
describe
  context
     it
``` 
will break the whole suites page. On the overview page this looks like:
![image](https://user-images.githubusercontent.com/55159635/85426111-a68c4880-b53f-11ea-8388-108dc5d8c1e4.png) 
Clicking on any of the above links will lead to a 404 page.
When i look at the generated allure report i'm finding a missing name field in the suites.json. I assume because it's being set to nil by the formatter. 
![image](https://user-images.githubusercontent.com/55159635/85427977-20253600-b542-11ea-9c5c-45363f2e57e6.png)
Also here's an example of the formatter produced result of one of these breaking test cases
```
fdescribe "Should break suites" do
  it "test passes" do
    expect(1).to be(1)
  end
end

result:
{
  "name": "test passes",
  "description": "Location - spec/break_suites_spec.rb:2",
  "descriptionHtml": "Location - spec/break_suites_spec.rb:2",
  "status": "passed",
  "statusDetails": {
    "known": false,
    "muted": false,
    "flaky": false
  },
  "stage": "finished",
  "steps": [],
  "attachments": [],
  "parameters": [],
  "uuid": "3d21cdd0-979d-0138-e6eb-2cde48001122",
  "historyId": "33e575d46ea1f03a61ac4560da35536a",
  "fullName": "Should break suites test passes",
  "labels": [
    {
      "name": "framework",
      "value": "rspec"
    },
    {
      "name": "feature",
      "value": "Should break suites"
    },
    {
      "name": "package",
      "value": "spec"
    },
    {
      "name": "story",
      "value": "test passes"
    },
    {
      "name": "testClass",
      "value": "break_suites_spec"
    },
    {
      "name": "severity",
      "value": "normal"
    },
    {
      "name": "suite",
      "value": "Should break suites"
    },
    {
      "name": "parentSuite"
    },
    {
      "name": "subSuite"
    },
    {
      "name": "thread",
      "value": 52140
    },
    {
      "name": "host",
      "value": "WalterBenson-35215.local"
    },
    {
      "name": "language",
      "value": "ruby"
    }
  ],
  "links": [],
  "start": 1592930028708,
  "stop": 1592930028709
}
```

**Comment by andrcuns** [comment]
Thanks for the bug report. I will take a look.

**Comment by andrcuns** [comment]
@walterbenson I did find an issue. Though it seems to be somewhat working with latest allure-cli (2.13.4), I couldn't get 404 error.

**Comment by andrcuns** [comment]
@walterbenson I released a fix, let me know if you encounter any other problems. I couldn't reproduce it anymore with allure-cli 2.13.4.

**Comment by walterbenson** [comment]
It works! Thanks for fixing it 💯 🥇 🚀
