### ISSUE TITLE
Console logs - Starting step and Stopping step logs missing with latest updates to allure-rspec

### ISSUE THREAD

**Issue by Manojv00087** [allure-framework/allure-ruby#143]
![image](https://user-images.githubusercontent.com/46107289/89295659-ed14ad00-d67e-11ea-90db-3a4dbdde2e83.png)

Previously When I'm running any spec files which contains test steps, I was able to see the starting and stopping steps logs on allure-rspec v0.8.0 - Now I don't see it after upgrading to latest version of allure-rspec to 2.13.6..

Please help me If I need to update some configs in my spec_helper or somewhere to get to see the logs

**Comment by andrcuns** [comment]
There is nothing to enable I am afraid. Since this is a complete rewrite and it basically only shares the name with previous allure-rspec gem, these log messages are simply not there.

I will add this as a feature to my list of things to do, I can see how this could be helpful in certain cases.
