### ISSUE TITLE
Can not add attachments using allure-ruby

### ISSUE THREAD

**Issue by priyankshah217** [allure-framework/allure-ruby#172]
I am not able to add attachment using allure-ruby bindings, as i am getting below message while adding attachments.
`E, [2020-10-22T19:06:34.186470 #56285] ERROR -- : Can't add attachment, no test, step or fixture is running`

while debugging `Allure.add_attachment` i found that  executable_item returns nil `executable_item = (test_case && @current_test_case) || current_executable` 

ruby version: 2.7.2
allure-rspec (2.13.6.3)
allure-ruby-commons (2.13.6.3)

Code snippet:
```
config.after(:each) do |example|
    clear_data
    if example.exception != nil
      screenshot_file_name = save_screenshot(file_path)
      Allure.add_attachment(name: screenshot_file_name, source: File.open(screenshot_file_name) , type: Allure::ContentType::PNG, test_case: true)
    end
end
```
Point is example project run fine locally.

Please help me to resolve this issue.

**Comment by priyankshah217** [comment]
Actually formatter was missing inside spec_helper.rb

**Comment by juliosantosjob** [comment]
@priyankshah217 you are right

I did it in my configuration project and defined this in the screenshots:

`
RSpec.configure do |config|
  config.formatter = AllureRspecFormatter
end

  config.after :each do |example|
    test_pass = example.exception.nil?

    capy_driver = Capybara.current_session.driver
    puts test_pass ? "Test successful!" : "Test fail!"
    puts "..."

    begin
      Dir.mkdir("logs") unless Dir.exist?("logs")
      shot_path = "logs/#{example.description.gsub(" ", "_").downcase}_" \
      "#{test_pass ? "passed" : "failed"}.png"

      capy_driver.save_screenshot(shot_path)
    rescue StandardError => e
      puts "Error: Unable to perform screenshot action! #{e.message}"
    end

    Allure.add_attachment(
      name: shot_path,
      type: Allure::ContentType::PNG,
      source: File.open(shot_path)
    )
  end
`

**Comment by Mona-Superscientist** [comment]
I'm trying a similar thing which doesn't work for me, formatter is added normally

```
require "rspec"
require "allure-rspec"
require "Pathname"

require_relative '../spec/allure_helper'

RSpec.configure do |config|
  config.add_formatter AllureRspecFormatter

  AllureRspec.configure do |c|
    c.results_directory = 'reports/allure-results'
    c.clean_results_directory = true
    c.logger = Logger.new($stdout, Logger::DEBUG)
    c.logging_level = Logger::INFO
  end

  config.after(:each) do |example|
    puts "after each is  being executed"
    puts "response in after each is #{@response}"
    if @response
      puts "im in the check ..."
      example.metadata[:response] = @response
      AllureHelper.attach_request_details_to_report(@response)
    end
  end

  config.expect_with :rspec do |expectations|
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  config.mock_with :rspec do |mocks|
    mocks.verify_partial_doubles = true
  end

  config.shared_context_metadata_behavior = :apply_to_host_groups
end
```
