### ISSUE TITLE
Nested steps annotations

### ISSUE THREAD

**Issue by Vikquick** [allure-framework/allure-ruby#216]
Hello! 
In other languages we have annotations for nested steps like 'Step' in java, 'allure.step' in python and etc.
So how can i make nested steps in Ruby? 

Shure i can make it like this:
```
# @param [String] name - name of a step
def run_step(name)
 Allure.run_step name do
    step name
  end
end


# Nested steps realization

Given(/^Make two steps$/) do
  run_step 'First step'
  run_step 'Second step'
end
```

And i`ll have something like this
![image](https://user-images.githubusercontent.com/28265560/107653353-f8363e80-6c9a-11eb-8154-f381b2813db9.png)

Also i can just pass blocks of code into Allure.run_step method with name param

But it only works for void methods, cause run_step method uses yield, right?
In Java i can write something like this

```
    @BeforeTest
    public void setUp() {
        saySomething();
    }

    @Step(value = "With name as a annotation value")
    private String saySomethingWithName() {
        return "keke";
    }

    @Step
    private void saySomething() {
        System.out.println(saySomethingWithName());
    }
```
And i`ll have this result
![image](https://user-images.githubusercontent.com/28265560/107654014-ac37c980-6c9b-11eb-8792-1ab40256b2a3.png)

So can you help me with solution of my problem?
1) Or i`m doing something wrong
2) Or would you kindly to answer: will this functionality ever be added?

**Comment by andrcuns** [comment]
@Vikquick Yes, indeed you are correct, it would work by simply nesting a `run_step` method inside a block of another `run_step` method, but it would not properly return the result, as currently the `run_step` method doesn't return result of yield.

There is also no additional methods or a way to mark methods as `steps` in a more convenient fashion. I haven't used manual steps method, thus didn't really think of such usecase.

Fixing `run_step` method to have a proper return value is a fairly easy fix, adding a more convenient way of marking methods as steps would require a bit more thought and some additional methaprogramming magic. 

Feel free to create a feature request for something like that. I would imagine it could be something like a method which you could add to your class and then call it with a list of method names to use as steps automatically:

```ruby

class MyClass
  include Allure
  
  steps :my_method, :my_method2

  def my_method
  end

  def my_method2
  end
end
```

**Comment by andrcuns** [comment]
FYI, latest version now has support for java like step annotation 🚀 

https://github.com/allure-framework/allure-ruby/blob/master/allure-ruby-commons/README.md#steps
