### ISSUE TITLE
Mess in feature and story tags

### ISSUE THREAD

**Issue by Kerem356** [allure-framework/allure-ruby#227]
Hi! I updated allure-rspec fron 0.8.0 -> 2.13.8.3 and found some strange behavior with tags. In particular feature and story tags.
Here code spec example for build report
```
describe 'Method', feature: '/some/method' do
  context 'GET', story: 'GET' do
    it 'should be success' do end
  end

  context 'POST', story: 'POST' do
    it 'should be success' do end
  end

  context 'PUT', story: 'PUT' do
    it 'should be success' do end
  end

  context 'DELETE', story: 'DELETE' do
    it 'should be success' do end
  end

  context 'PATCH', story: 'PATCH' do
    it 'should be success' do end
  end
end
```

On 0.8.0 version i got nice structure in Behavior section

![image](https://user-images.githubusercontent.com/13794799/109153622-32650d00-777e-11eb-8b4d-c55f75d0d145.png)

But when i built report on last release version i found that structure is changed and started to look like this

![image](https://user-images.githubusercontent.com/13794799/109153785-67715f80-777e-11eb-94ff-73c783fa3c30.png)

Story has become a feature. Example name has become a story. Feature is go away :-) 
Looks like a mess :-)

Or it's new cool allure ruby style?

**Comment by andrcuns** [comment]
I appreciate your reporting style. Feel free and keep using the 0.8.0 or better yet implement your own adapter to not get any mess in your reports ;)

As to how to get same result with this reporter. Tags with names `story` or `feature` have no special effect, just use native rspec structures like `describe` and `context` to group the tests.

So this:
```ruby
describe '/some/method' do
  context 'GET' do
    it 'should be success' do end
  end

  context 'POST' do
    it 'should be success' do end
  end

  context 'PUT' do
    it 'should be success' do end
  end

  context 'DELETE' do
    it 'should be success' do end
  end

  context 'PATCH' do
    it 'should be success' do end
  end
end
```

will look like this under Suites tab:
<img width="807" alt="image" src="https://user-images.githubusercontent.com/12693088/109179461-972a6280-7792-11eb-82e8-e276b9427d47.png">

which is exactly how rspec itself is reporting:

```shell
$ bundle exec rspec
/some/method
  GET
    should be success
  POST
    should be success
  PUT
    should be success
  DELETE
    should be success
  PATCH
    should be success

Finished in 0.01448 seconds (files took 0.38322 seconds to load)
5 examples, 0 failures
```

**Comment by Kerem356** [comment]
Hi, @andrcuns ! I understood your point and own adapter will be better solution for me.  Thx for help! ✌️
