### ISSUE TITLE
Tags are empty for rspec tests

### ISSUE THREAD

**Issue by vkodimut** [allure-framework/allure-ruby#252]
Hi There,

I am using `allure-rspec (0.8.0)`  for rspec tests and `allure-cucumber(2.13.4)` for cucumber tests. I am able to see the tags displayed in allure report for cucumber tests eg in output.json.
```
 },
    "tags" : [ "sidekiq", "js" ]
  },
  "source" : "fdd25b33e227a5b5.json",
```
But for rspec I see an empty array `"tags": []` 

Currently have few rspec test with tags as `context "test case", important: true do` and `it "new test case", data: "postgres" do`.
I would like these tags to display in the output json.
I tried upgrading to allure-rspec 2.13.4 but no luck & face 404 when clicked on tests in allure report so have to go with 0.8.0

Could you please help or suggest !!

**Comment by andrcuns** [comment]
`allure-rspec` version `0.8.0` comes from a different repository which has been archived for a while now. My only suggestion is to update everything to the latest versions.

It's hard for me to imagine why more recent version of `allure-cucumber` would work, but not a more recent version of `allure-rspec`.

**Comment by andrcuns** [comment]
You can also check this repository for an example setup with latest `allure-rspec` version: https://github.com/allure-examples/allure-rspec-example
