### ISSUE TITLE
Updated gem for port of Rspec Allure

### ISSUE THREAD

**Issue by hughleo** [allure-framework/allure-ruby#27]
I see this has been completed - https://github.com/allure-framework/allure-ruby/issues/3, but unless I'm missing something the gem for Rspec allure hasn't actually been updated yet? Will this be done soon?

**Comment by andrcuns** [comment]
Yes, it hasn't been released yet. Should be done in nearest future I think. cc: @eroshenkoam @baev

**Comment by hughleo** [comment]
Sorry I should have also said - thanks so much for your hard work! Looking forward to trying out the new version
