### ISSUE TITLE
Same test case goes for a retry section even though being specified with custom environment

### ISSUE THREAD

**Issue by eduardrudko** [allure-framework/allure-ruby#307]
Hello, good afternoon!

I've tried so far quite a lot, and i really have difficulties to establish a correct reporting for distributed execution. 
Quick context: i have a pipeline which executes the same test on different drivers on separate nodes and afterwards aggregates results and generates report.

`  gem "allure-cucumber", "2.13.6"
`
**first execution yields:**
*-result.json
`{
  "name": "[chrome]::Test Case",
  "description": "Location - Test_Case_path:5",
  "descriptionHtml": "Location - Test_Case_path:5",
  "status": "passed",
  "statusDetails": {
    "known": false,
    "muted": false,
    "flaky": false
  },
  "stage": "finished",
  "steps": [
    {
      "name": "Given user is on the home page",
      "status": "passed",
      "statusDetails": {
        "known": false,
        "muted": false,
        "flaky": false
      },
      "stage": "finished",
      "steps": [],
      "attachments": [],
      "parameters": [],
      "start": 1628172063660,
      "stop": 1628172067761
    }
  ],
  "attachments": [],
  "parameters": [],
  "uuid": "7cbe0fc0-d823-0139-9e5b-2cde48001122",
  "historyId": "3afbc22fe9895d3cfa2743a512c8854c",
  "fullName": "Static pages: [chrome]::Test Case",
  "labels": [
    {
      "name": "framework",
      "value": "cucumber"
    },
    {
      "name": "feature",
      "value": "[chrome]::Static pages"
    },
    {
      "name": "package",
      "value": "[chrome]::static_pages"
    },
    {
      "name": "suite",
      "value": "[chrome]::Static pages"
    },
    {
      "name": "story",
      "value": "[chrome]::User closes Cookie Banner modal"
    },
    {
      "name": "testClass",
      "value": "[chrome]::cookie_banner"
    },
    {
      "name": "tag",
      "value": "regression"
    },
    {
      "name": "severity",
      "value": "normal"
    },
    {
      "name": "thread",
      "value": 70365359570900
    },
    {
      "name": "language",
      "value": "ruby"
    },
    {
      "name": "host",
      "value": "chrome"
    }
  ],
  "links": [],
  "start": 1628172060079,
  "stop": 1628172074768
}
`

*-container.json
`{
  "uuid": "7cbe0620-d823-0139-9e5b-2cde48001122",
  "name": "[chrome]::Test Case",
  "children": [
    "7cbe0fc0-d823-0139-9e5b-2cde48001122"
  ],
  "befores": [
    {
      "name": "hooks.rb:9",
      "status": "passed",
      "statusDetails": {
        "known": false,
        "muted": false,
        "flaky": false
      },
      "stage": "finished",
      "steps": [],
      "attachments": [],
      "parameters": [],
      "start": 1628172060079,
      "stop": 1628172063041
    },
    {
      "name": "hooks.rb:33",
      "status": "passed",
      "statusDetails": {
        "known": false,
        "muted": false,
        "flaky": false
      },
      "stage": "finished",
      "steps": [],
      "attachments": [],
      "parameters": [],
      "start": 1628172063041,
      "stop": 1628172063660
    }
  ],
  "afters": [
    {
      "name": "hooks.rb:20",
      "status": "passed",
      "statusDetails": {
        "known": false,
        "muted": false,
        "flaky": false
      },
      "stage": "finished",
      "steps": [],
      "attachments": [],
      "parameters": [],
      "start": 1628172074570,
      "stop": 1628172074767
    }
  ],
  "links": [],
  "start": 1628172060079,
  "stop": 1628172074770
}
`

**second execution yields:**

_*-results.json_
`{
  "name": "[chrome_iphone_x]::Test Case",
  "description": "Location - Test_Case_path:5",
  "descriptionHtml": "Location - Test_Case_path:5",
  "status": "passed",
  "statusDetails": {
    "known": false,
    "muted": false,
    "flaky": false
  },
  "stage": "finished",
  "steps": [
    {
      "name": "Given user is on the home page",
      "status": "passed",
      "statusDetails": {
        "known": false,
        "muted": false,
        "flaky": false
      },
      "stage": "finished",
      "steps": [],
      "attachments": [],
      "parameters": [],
      "start": 1628172124046,
      "stop": 1628172128148
    }
  ],
  "attachments": [],
  "parameters": [],
  "uuid": "a0fb4080-d823-0139-9e5c-2cde48001122",
  "historyId": "3afbc22fe9895d3cfa2743a512c8854c",
  "fullName": "Static pages: [chrome_iphone_x]::Test Case",
  "labels": [
    {
      "name": "framework",
      "value": "cucumber"
    },
    {
      "name": "feature",
      "value": "[chrome_iphone_x]::Static pages"
    },
    {
      "name": "package",
      "value": "[chrome_iphone_x]::static_pages"
    },
    {
      "name": "suite",
      "value": "[chrome_iphone_x]::Static pages"
    },
    {
      "name": "story",
      "value": "[chrome_iphone_x]::Test Case"
    },
    {
      "name": "testClass",
      "value": "[chrome_iphone_x]::Test Case"
    },
    {
      "name": "tag",
      "value": "regression"
    },
    {
      "name": "severity",
      "value": "normal"
    },
    {
      "name": "thread",
      "value": 70176993378260
    },
    {
      "name": "language",
      "value": "ruby"
    },
    {
      "name": "host",
      "value": "chrome_iphone_x"
    }
  ],
  "links": [],
  "start": 1628172120878,
  "stop": 1628172134911
}
`
_*-container.json_
`{
  "uuid": "a0fb3740-d823-0139-9e5c-2cde48001122",
  "name": "[chrome_iphone_x]::Test Case",
  "children": [
    "a0fb4080-d823-0139-9e5c-2cde48001122"
  ],
  "befores": [
    {
      "name": "hooks.rb:9",
      "status": "passed",
      "statusDetails": {
        "known": false,
        "muted": false,
        "flaky": false
      },
      "stage": "finished",
      "steps": [],
      "attachments": [],
      "parameters": [],
      "start": 1628172120878,
      "stop": 1628172123420
    },
    {
      "name": "hooks.rb:33",
      "status": "passed",
      "statusDetails": {
        "known": false,
        "muted": false,
        "flaky": false
      },
      "stage": "finished",
      "steps": [],
      "attachments": [],
      "parameters": [],
      "start": 1628172123420,
      "stop": 1628172124046
    }
  ],
  "afters": [
    {
      "name": "hooks.rb:20",
      "status": "passed",
      "statusDetails": {
        "known": false,
        "muted": false,
        "flaky": false
      },
      "stage": "finished",
      "steps": [],
      "attachments": [],
      "parameters": [],
      "start": 1628172134727,
      "stop": 1628172134911
    }
  ],
  "links": [],
  "start": 1628172120878,
  "stop": 1628172134915
}
`

As you can see almost every attribute is unique, key word here almost. 

I've tried the same on last allure-cucumber version and i get the same results.

<img width="1266" alt="Screenshot 2021-08-05 at 17 23 26" src="https://user-images.githubusercontent.com/38434976/128366664-ca1abe2e-f73a-4143-811e-101ea4fc965a.png">

**Comment by andrcuns** [comment]
Hello,

The custom environment support was properly implemented only starting from version [2.14.1](https://github.com/allure-framework/allure-ruby/releases/tag/2.14.1). Starting from this version, it should properly differentiate the tests running on different environments given environment is set properly like described in [documentation](https://github.com/allure-framework/allure-ruby/blob/master/allure-ruby-commons/README.md#allure-execution-environment)

**Comment by eduardrudko** [comment]
Indeed, works on 2.14.3. Thanks @andrcuns for point this out.
