### ISSUE TITLE
Suites names are not displayed

### ISSUE THREAD

**Issue by ivodimitrov** [allure-framework/allure-ruby#330]
Hello! 

I'm using version 2.13.4. 
My current setup is:

- at `Gemfile`: 
`gem 'allure-rspec', '= 2.13.4'`

- at `.rspec` file:
```
--require spec_helper
--color
--format documentation
--format AllureRspecFormatter
```
- at `spec_helper.rb`:
```ruby
require 'allure-rspec'

Allure.configure do |c|
  c.results_directory = 'results/allure-results'
  c.clean_results_directory = true
  c.logging_level = Logger::DEBUG
  c.link_tms_pattern = 'https://....testrail.net/index.php?/cases/view/{}'
  c.link_issue_pattern = 'https://trello.com/c/{}'
end

RSpec.configure do |config|
 config.formatter = AllureRspecFormatter

config.after do |e|
    Allure.step name: e
    Allure.add_attachment(
      name: e.full_description,
      source: @browser.screenshot.png,
      type: Allure::ContentType::PNG,
      test_case: true
    )
  end

  config.after :all do
    @browser.close
    envfile = FileWrite.new 'results/allure-results/environment.properties'
    envfile.write_allure_env
  end
end
```
- at `any_spec` file:
```ruby
describe '[Smoke] Client', :smoke do

it 'logs into their account', tms: '12149' do
    # test code and assertions
  end
```

I'm struggling with: 

1. Suites names are not displayed on Overview page:
![Screenshot 2021-11-11 at 19 33 40](https://user-images.githubusercontent.com/14165628/141343116-d201a3db-f80f-49d7-b094-bcda0dfb75b1.png)

2. `component.tree.unknown` is displayed on Suites page:
![Screenshot 2021-11-11 at 19 35 02](https://user-images.githubusercontent.com/14165628/141343466-c9c3924f-7e7c-4066-8700-6e1cd91e81f8.png)

Could you please support me how to setup suites names and not having: `component.tree.unknown`?
I could not find solution at [official documentation](https://docs.qameta.io/allure/), neither at stackoverflow.

Many thanks in advance!

**Comment by andrcuns** [comment]
Hi!

You should definitely start with updating to latest version. There has been many bugfixes and improvements since then, so that might resolve the problem.

**Comment by ivodimitrov** [comment]
I will try to update to latest version 2.15

**Comment by ivodimitrov** [comment]
I will try to update to latest version 2.15

**Comment by Guoxiaoyun0718** [comment]
Hello, I also encountered the same problem as you. Did you solve it by upgrading the version?

**Comment by ivodimitrov** [comment]
> Hello, I also encountered the same problem as you. Did you solve it by upgrading the version?

Yes, latest version eliminates all my previous struggles. Please also read my other [closed issue](https://github.com/allure-framework/allure-ruby/issues/331) about upgrade
