### ISSUE TITLE
Could not update to version greater than 2.13.6

### ISSUE THREAD

**Issue by ivodimitrov** [allure-framework/allure-ruby#331]
Hello! 

I'm using version **2.13.4**. 
My current setup is:

- at `Gemfile`: 
`gem 'allure-rspec', '= 2.13.4'`

- at `.rspec` file:
```
--require spec_helper
--color
--format documentation
--format AllureRspecFormatter
```

- at `spec_helper.rb`:
```ruby
require 'allure-rspec'

Allure.configure do |c|
  c.results_directory = 'results/allure-results'
  c.clean_results_directory = true
  c.logging_level = Logger::DEBUG
  c.link_tms_pattern = 'https://....testrail.net/index.php?/cases/view/{}'
  c.link_issue_pattern = 'https://trello.com/c/{}'
end

RSpec.configure do |config|
 config.formatter = AllureRspecFormatter

config.after do |e|
    Allure.step name: e
    Allure.add_attachment(
      name: e.full_description,
      source: @browser.screenshot.png,
      type: Allure::ContentType::PNG,
      test_case: true
    )
  end

  config.after :all do
    @browser.close
    envfile = FileWrite.new 'results/allure-results/environment.properties'
    envfile.write_allure_env
  end
end
```

- at `any_spec` file:
```ruby
describe '[Smoke] Client', :smoke do

it 'logs into their account', tms: '12149' do
    # test code and assertions
  end
```

When I'm trying to update to latest version **2.15**, I'm struggling with an error:

```
Failure/Error: Allure.step name: e

     NoMethodError:
       undefined method `steps' for nil:NilClass
     # ./spec/spec_helper.rb:99:in `block (2 levels) in <top (required)>'
```

Could you please help! Many thanks in advance!

**Comment by ivodimitrov** [comment]
After hours of debugging, I found out that:

```ruby
RSpec.configure do |config|
 config.formatter = AllureRspecFormatter
```

must be removed.

**Comment by andrcuns** [comment]
Technically passing `--format AllureRspecFormatter` is the same as configuring it via `config.formatter = AllureRspecFormatter`. Rather strange it would fail if both options are provided.

The failure here seems to happen due to not having a running test case when executing `Allure.step name: e`

**Comment by ivodimitrov** [comment]
My project actually having `--format AllureRspecFormatter` at `.rspec` and `config.formatter = AllureRspecFormatter` at `spec_helper.rb`. 
So probably this cause the error. I left only `--format AllureRspecFormatter` at `.rspec` and now everything works fine.

**Comment by andrcuns** [comment]
It's ok, I did understand what You meant in the previous comment. I find it rather strange that it caused failure when both options were provided, might be that some bug is hiding somewhere that doesn't properly handle something when both options are there. In theory it shouldn't matter.

Anyhow, glad it worked out

**Comment by ivodimitrov** [comment]
There is something else I would like to ask about ver. 2.15. Sorry it is not related to upgrade, nor to `AllureRspecFormatter `, but I do not want to open new issue.

When at `any_spec.rb` file there are tags, this tags are displayed in the report.
Example:
```ruby
describe '[Regression] Partner', :regression, local: false do
```
<img width="664" alt="Screenshot 2021-11-16 at 10 37 57" src="https://user-images.githubusercontent.com/14165628/141951411-114f574b-77c0-4679-aa62-2ab0cda2e5d9.png">

Shouldn't tags set to false `local: false` been excluded?

**Comment by andrcuns** [comment]
Current logic is not checking the actual value of the tag, it simply adds all keys to allure as tags. But it might be beneficial to not add if the value is explicitly false
