### ISSUE TITLE
Add support for parameters in step

### ISSUE THREAD

**Issue by MohamedAsan** [allure-framework/allure-ruby#346]
Allure Report supports parameters in steps. It would be very useful to display the parameters in each step for easier debugging

<img width="1536" alt="Allure - Step Parameters" src="https://user-images.githubusercontent.com/29650842/150625950-b9d4275b-e78c-4886-a2f6-88ecafbdd6b2.png">

**Comment by MohamedAsan** [comment]
@andrcuns I have made the necessary changes as well - https://github.com/allure-framework/allure-ruby/compare/master...MohamedAsan:master

**Comment by andrcuns** [comment]
@MohamedAsan Great! Feel free to open a PR.
