### ISSUE TITLE
Add support for influencing history id based on environment properties

### ISSUE THREAD

**Issue by adfoster-r7** [allure-framework/allure-ruby#494]
Scenario:

When running the same test suite against in parallel against different host operating systems (i.e. mac/linux/windows), I noticed that the some test results were missing from the generated `suites` page after generating the allure report - but the test runs were available in the timeline view

I tracked this down to the results `historyId` being re-used multiple times across my runners:

```json5
{
  // ...
  "parameters": [
    {
      "name": "environment",
      "value": "darwin19"
    }
  ],
  "uuid": "6c9a7870-dff7-013b-1c3f-005056a70044",
  "historyId": "5fadf4ef80bc505e534df630bc674529",
  // ...
}
```

Digging deeper, I noticed that the value being generated is based on the `example.id`, i.e. `"./spec/acceptance/foo_spec.rb[1:2:1:1:11:1]` - which won't be unique when running the test suite on different github action runners in parallel against windows/linux/macos

https://github.com/allure-framework/allure-ruby/blob/ec4f9901f241b177bdd83528e9046cd8646f29de/allure-rspec/lib/allure_rspec/formatter.rb#L109

It would be great if we could influence the history id in some capacity, so that the environment properties could be considered too

**Comment by andrcuns** [comment]
It is actually influenced by environment. It happens when generating the unique id string based on the passed example id: https://github.com/allure-framework/allure-ruby/blob/master/allure-ruby-commons/lib/allure_ruby_commons/model/test_result.rb#L27

So the problem must be something else.

**Comment by adfoster-r7** [comment]
Thanks for taking a look :+1:

With fresh eyes; I believe the current implementation is honoring `allure_config.environment`, but not taking into consideration the values in `allure_config.environment_properties`

For context I believe this was the example I originally followed from the docs:

https://github.com/allure-framework/allure-ruby/blob/ae019564c2869194408eab1a9522361be5bfdae1/allure-rspec/README.md?plain=1#L21-L45

Current values:

```
[3] pry(#<AllureRspec::RSpecFormatter>)> allure_config.environment
=> "darwin20"
[4] pry(#<AllureRspec::RSpecFormatter>)> allure_config.environment_properties
=> {:host_os=>"darwin20", :ruby_version=>"3.0.5"}
```

I would have expected the `allure_config.environment_properties` to influence the history id.
I think this also explains why my properties weren't appearing here in the Allure report either:

<img width="525" alt="image" src="https://github.com/allure-framework/allure-ruby/assets/60357436/063b65d3-03ba-4308-af89-ddda73ed3b2f">

Let me know if this is user error, or something that needs to be tweaked :+1:

**Comment by andrcuns** [comment]
environment.properties file indeed is not taken in consideration because it's not really test related thing from report perspective, it's what generates the `Environment` section on the main page, like so:
![image](https://github.com/allure-framework/allure-ruby/assets/12693088/76e43dae-9d39-4933-8795-c33522e2ec47)

The parameter `environment` in the test itself however is slightly different, it can only be a single value and there can't be several `environment` properties. It's main purpose is to differentiate same specs running on different environments so they are not dropped in to retries.

But I can see how you could have multi-dimensional run matrix, so one parameter isn't enough, maybe there is a better way, not 100% sure.

**Comment by andrcuns** [comment]
cc: @baev 

I have not been following super closely how other adapters implement similar functionality lately, maybe there is something to improve here?

**Comment by adfoster-r7** [comment]
> I can see how you could have multi-dimensional run matrix, so one parameter isn't enough

That's my exact scenario :+1: I'm testing the same library code by running the same test suite against different operating systems and ruby combinations with Github action's matrix

**Comment by andrcuns** [comment]
The main problem is that `environment.properties` can have data that should not be taken in to account when generating history id, like app versions, revisions etc and there is no real way to know that.

The default `environment` functionality just uses built in `allure` parameter functionality to create a parameter named `environment`. But You can also just set those parameters yourself via `parameter` helper method.

```ruby
before do |example|
  example.parameter("ruby", "3.1")
  example.parameter("os", "darwin20")
end
```

Full list of parameters is still not taken in to account when generating history_id which actually is a bug now that I think about it.

**Comment by adfoster-r7** [comment]
Thanks for pointing that API out, my parameters are now correctly tracked in the UI now - but the history id still isn't changed based on those values as you say :+1:
