### ISSUE TITLE
Allure Report shows incorrect calculations for failed tests because of test retries

### ISSUE THREAD

**Issue by kirannandarapalli** [allure-framework/allure-ruby#512]
We have a retries(2) option that is configured in our framework to retry when we have a failed test. Recently, we upgraded the allure-cucumber gem from 2.14.3 to 2.23.0, and due to this we see the allure report showing all the retries in the report which leads to wrong calculation of failures

Also, the report shows that failure even though the test passed a second-time retry

Ex: Test 1 - Failed
       Retry Test 1 - Passed
The report shows that both Test 1 passed and Retry 1 failed

**Comment by andrcuns** [comment]
I tried to reproduce the problem and don't really see an issue here. The report displays everything correctly with retry of a failed test. Consider following example from https://github.com/allure-examples/allure-cucumber-example:

```console
$ bundle exec cucumber --retry 1 features/flaky.feature
Using the default profile...
Feature: flaky test example

  Scenario: Passes on the second try # features/flaky.feature:3
    Given I am a flaky test          # features/step_definitions/common_steps.rb:7
    When I run this test             # features/step_definitions/common_steps.rb:15
    Then it passes on the second try # features/step_definitions/common_steps.rb:31

      expected: 2
           got: 1

      (compared using ==)
       (RSpec::Expectations::ExpectationNotMetError)
      ./features/step_definitions/common_steps.rb:32:in `"it passes on the second try"'
      features/flaky.feature:6:in `it passes on the second try'

  Scenario: Passes on the second try # features/flaky.feature:3
    Given I am a flaky test          # features/step_definitions/common_steps.rb:7
    When I run this test             # features/step_definitions/common_steps.rb:15
    Then it passes on the second try # features/step_definitions/common_steps.rb:31



1 scenario (1 flaky)
6 steps (1 failed, 5 passed)
0m0.017s
```

This will produce report with 1 passing example but with an indicator that status failed on retry:
<img width="1545" alt="image" src="https://github.com/allure-framework/allure-ruby/assets/12693088/a6ebd653-e606-4ef1-9784-05bcb733b133">

The retry tab will contain first failed run:
<img width="1547" alt="image" src="https://github.com/allure-framework/allure-ruby/assets/12693088/3266ece3-a3e8-4a6d-9b62-7dcda8bf6237">

This seems to be exactly the behavior expected from a retry.
