### ISSUE TITLE
Enable terminal output of test results when using AllureRspecFormatter

### ISSUE THREAD

**Issue by hatsu38** [allure-framework/allure-ruby#532]
Thank you for developing and maintaining it!

## Problem Description

When using the `AllureRspecFormatter`, the test results are not displayed in the terminal, which is different from the default behavior when no formatter is specified. This makes it difficult to quickly assess the status of tests during development and CI processes.

## Expected Behavior

It would be beneficial to have an option or configuration that allows the test results to be displayed in the terminal while also using `AllureRspecFormatter` to generate the Allure reports. This would provide immediate feedback in the terminal, as well as the detailed reports generated by Allure.

**Comment by andrcuns** [comment]
`AllureRspecFormatter` does not produce any console output so there is nothing to enable really. 

To retain console output, in addition to `AllureRspecFormatter`, you need to specify one of the built in console formatters, like `--format documentation` for example.

**Comment by hatsu38** [comment]
Ah, Got it. 
So, I can specify multiple formatters at the same time, like AllureRspecFormatter along with --format documentation. 
Thanks! That seems like it will solve my issue!
