### ISSUE TITLE
Allure Rspec: category page 404 error

### ISSUE THREAD

**Issue by kamalakannan-chockalingam** [allure-framework/allure-ruby#544]
Currently, when loading the category page in our Allure report, we encounter a 404 error. Upon debugging, it appears that this error occurs when an exception is passed as `nil` to the Allure::ResultUtils::status_details method.

![404_allure](https://github.com/allure-framework/allure-ruby/assets/41687640/cca7da50-7e12-45ed-89d6-bc950961f4a2)

**Comment by kamalakannan-chockalingam** [comment]
Found a similar implementation in the Java framework: https://github.com/allure-framework/allure-java/pull/183/files. 

Updated similar kind of implementation [here](https://github.com/allure-framework/allure-ruby/compare/master...kamalakannan-chockalingam:allure-ruby:allure_404?expand=1) for ruby.

@andrcuns Can you please check and provide your input.

**Comment by andrcuns** [comment]
@kamalakannan-chockalingam Could You please create actual pull request?

**Comment by kamalakannan-chockalingam** [comment]
> @kamalakannan-chockalingam Could You please create actual pull request?

Created a PR for that: https://github.com/allure-framework/allure-ruby/pull/546

**Comment by andrcuns** [comment]
@kamalakannan-chockalingam I have reverted the fix that was introduced for this issue because it actually introduced a bug where status detail now has `NilClass` for all passed tests.

Could you try and create a reproducible example in order to create a proper fix for issue you were observing?

**Comment by kamalakannan-chockalingam** [comment]
Sure will check from my side, Thanks @andrcuns.
