### ISSUE TITLE
New feature - Wrapping of text for Allure step output

### ISSUE THREAD

**Issue by samuel-anbudaiyan** [allure-framework/allure-ruby#562]
The Allure step status method output text could be wrapped in one or two lines and the report would be UI friendly.
<img width="802" alt="image" src="https://github.com/user-attachments/assets/7434a1ce-1a35-4c03-be8d-1dc8d7df0b2b">

**Comment by andrcuns** [comment]
Could You please be more specific on what this proposes? Wrapping/Trimming step names?

I'm not sure how relevant such feature is. I think it's better to make sure you don't have random large texts in step names considering allure is supposed to support BDD where step names should be concise, short and describe the actions performed in the test clearly.

**Comment by andrcuns** [comment]
> @andrcuns In my case, i need to print the json api response in the report which is very big in this case and it looks ugly. If the output is wrapped in one or lines and then made expandable upon clicking, it could be useful. Also it is not for wrapping step names, it is for wrapping log step output.

You should probably add these api responses as json file attachments then, not dump it in the step name.

I will close this issue, because what you want to achieve is not doable in this repository. It would require implementation in the report itself: https://github.com/allure-framework/allure2
