### ISSUE TITLE
Step where response is returned inside Allure.run_step shows as if broken in report

### ISSUE THREAD

**Issue by harshithaa-murali5** [allure-framework/allure-ruby#563]
When the response is returned within Allure `run_step` block, the step is shown with yellow mark (as though broken), but if the same response is returned outside `run_step` block, it shows with green indication. Is this a feature or a bug?

Code:
```
def method1(input1 = nil)
  response = nil
  Allure.run_step "Method 1 validation" do
    Allure.step(name: "inbetween")
    response = "executed 1"
    return response
  end
end

def method2(input1 = nil)
  response = nil
  Allure.run_step "Method 2 validation" do
    Allure.step(name: "inbetween")
    response = "executed 2"
  end
  return response
end
```
```
it 'sample', :smoke do
  method1(input1 = {})
  method2(input1 = {})
end
```
![Screenshot 2024-08-22 at 11 47 21 AM](https://github.com/user-attachments/assets/efd079d6-9190-429a-a0ca-4e393af9963b)

**Comment by andrcuns** [comment]
You shouldn't be using `return` inside a block because it returns from the whole method not allowing for `run_step` method to complete correctly.

`run_step` itself returns result of the block by default, so You should simply do the following:

```ruby
def method2(input1 = nil)
  Allure.run_step "Method 2 validation" do
    Allure.step(name: "inbetween")
    
    "executed 2"
  end
end
```
