### ISSUE TITLE
allure-ruby - reports are not generated, error => `require': cannot load such file -- allur_rspec_formatter (LoadError) and `title': wrong number of arguments

### ISSUE THREAD

**Issue by Vito300187** [allure-framework/allure-ruby#99]
Can you tell me what the problem with starting and generating reports might be ? For reports, I use 
 allure-rspec with stack - ruby + rspec + capybara.

The installation process was performed in the following order

`brew install allure - (Version 2.13.2)`
`allure generate path`

enabled dependencies in spec_helper:
`require 'allure-rspec'`

```
RSpec.configure do |config|
  include AllureRSpec::Adaptor
  config.formatter = AllureRspecFormatter
...
end
```

```
AllureRSpec.configure do |config|
  config.output_dir = 'report/allure-results'
  config.clean_dir = false
  config.logging_level = Logger::DEBUG
end
```

1) When I running the test, `HEADLESS= "MY_ARTEC_URL= 'URI' rspec /absolute path to the file --format documentation --format AllurRspecFormatter --out rspec.xml`, error => [https://pastebin.com/NNrfn7Yq](https://pastebin.com/NNrfn7Yq)
I see that there is a problem with allur_rspec_formatter, but I do not understand how to set something separately and prescribe it in the settings.
I also took it out separately in Rakefile, but the error didn't disappear

```
RSpec::Core::RakeTask.new(:test) do |task|
task.rspec_opts = '--color --require spec_helper --format documentation --format AllureRspecFormatter'
task.verbose = false
end
```

2)  When I running the test, 
`HEADLESS='' rspec path --format documentation --out rspec_results.xml` 
 error already => ` 'title': wrong number of arguments` [https://pastebin.com/YWb20sEb](https://pastebin.com/YWb20sEb)`

3) When I running the test, `HEADLESS='' rspec path`, similar error => `
'title': wrong number of arguments `

Tell me where to dig or what I incorrectly configured / under- configured / under- installed / did not take into account ?

**Comment by andrcuns** [comment]
Yes, remove unsupported old configuration options.

You either need to provide formatter via rspec options
```bash
--format AllureRspecFormatter`
```
or through rspec configuration
```ruby
RSpec.configure do |c|
  c.formatter = AllureRspecFormatter
end
```
Also there is no rspec specific allure config, so Allure config should be used directly
```ruby
Allure.configure do |config|
  config.results_directory = "/whatever/you/like"
  config.clean_results_directory = true
  config.logging_level = Logger::INFO
end
```

Check [spec_helper.rb](https://github.com/allure-examples/allure-rspec-example/blob/master/spec/spec_helper.rb) for reference. It's all in the docs.
